
name: biencubierto
description: Aplicación móvil para gestión de seguros
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  equatable: ^2.0.5
  dartz: ^0.10.1


  flutter_secure_storage: ^8.0.0
  local_auth: ^2.1.6
  http: ^1.3.0
  provider: ^6.0.5
  screen_protector: ^1.3.0
  device_info_plus: ^9.0.3
  freezed_annotation: 2.4.1
  go_router: ^13.0.1
  riverpod_annotation: ^2.3.3
  json_annotation: ^4.8.1
  custom_lint: ^0.6.2
  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  flutter_riverpod: ^2.4.9
  country_picker: ^2.0.20
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

  flutter_lints: ^3.0.1
  freezed: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  generate: true 
  uses-material-design: true
  assets:
    - assets/logo/

flutter_gen:
  synthetic-package: false